services:
     lex_tree.tree-manager:
             class: Lex\TreeBundle\Manager\TreeManager
             arguments: ['@doctrine.orm.entity_manager' , "TreeBundle:Tree"]
#                 entityManager: @doctrine.orm.entity_manager
#                 repositoryName: "TreeBundle:Tree"
