services:
     lex_tree.tree-manager:
             class: Lex\TreeBundle\Manager\TreeManager
             arguments:
                 entityManager: "@doctrine.orm.entity_manager"
                 repositoryName: "TreeBundle:Tree"
